rollex <- function(x, k = 5){
  require(zoo)
  # Extended rolling mean, fill the extremeties with linear approximation
  roll <- rollmean(x, k, na.pad = T)
  NonNAindex <- which(!is.na(roll))
  fst <- min(NonNAindex)
  lst <- max(NonNAindex)
  
  # Left and Right slopes
  lslope <- (roll[fst + 1] - roll[fst]) / 2
  rslope <- (roll[lst] - roll[lst - 1]) / 2
  
  # Replace NAs generated by roll with approx
  for(i in 1:(fst-1)){
    roll[i] <- roll[fst] + lslope * (i - fst) 
  }
  for(i in (lst+1):length(roll)){
    roll[i] <- roll[lst] + rslope * (i - lst) 
  }
  return(roll)
}

clip <- function(x, y){
  # Take two numeric vectors of same length, set x to 1 when above y and x to 0 when below y
  return(ifelse(x >= y, 1, 0))
}

library(zoo)
Cora <- fread("C:/Users/pixel/Dropbox/Marc-Antoine/data/set1-Coralie/tCoursesSelected.csv")
Cora[, Ratio := objCyto_Intensity_MeanIntensity_imErkCorrOrig / objNuc_Intensity_MenIntensity_imErkCorrOrig]
setkey(Cora, Image_Metadata_Site)

tr1 <- Cora[Well == 6 & objNuc_TrackObjects_Label == 2, Ratio]
roll1 <- rollmean(tr1, k = 5, na.pad = T)
roll2 <- rollex(tr1, k = 5)
tr1_clip <- clip(tr1, roll2)

plot(tr1, type= "b", ylim = c(-0.1,1.1))
lines(roll1, type= "l", col="blue")
lines(roll2, type="l", col='red')
lines(tr1_clip, type="l", col="blue")

